# Generated by Django 5.1.4 on 2025-01-10 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_options_remove_user_username_user_avatar_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="city",
            field=models.CharField(
                blank=True,
                help_text="Введите город",
                max_length=50,
                null=True,
                verbose_name="Город",
            ),
        ),
    ]
