# Generated by Django 5.1.4 on 2025-01-30 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="link_to_pay",
            field=models.URLField(
                blank=True,
                help_text="Добавьте ссылку на оплату",
                max_length=400,
                null=True,
                verbose_name="Ссылка на оплату",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="session_id",
            field=models.CharField(
                blank=True,
                help_text="Введите ID сессии",
                max_length=255,
                null=True,
                verbose_name="ID сессии",
            ),
        ),
    ]
