# Generated by Django 5.1.4 on 2025-01-10 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0002_alter_lesson_link_to_the_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="link_to_the_video",
            field=models.URLField(
                blank=True,
                help_text="Добавьте ссылку на урок",
                null=True,
                verbose_name="Ссылка на урок",
            ),
        ),
    ]
